name: Trigger auto deployment for container-app-nwldftluiyd5g

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-nwldftluiyd5g-AutoDeployTrigger-7d9a1202-7190-47fc-a413-de32a0885b21.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPNWLDFTLUIYD5G_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPNWLDFTLUIYD5G_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPNWLDFTLUIYD5G_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPNWLDFTLUIYD5G_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPNWLDFTLUIYD5G_REGISTRY_PASSWORD }}
          containerAppName: container-app-nwldftluiyd5g
          resourceGroup: ehchatbottemplateb902
          imageToBuild: default/container-app-nwldftluiyd5g:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


